version: 0.0
os: linux
files:
    - source: /
      destination: /home/webapp/laravelsample_source
permissions:
    - object: /home/webapp/laravelsample_source
      pattern: "**"
      owner: nginx
      group: nginx
      mode: 755
      type:
        - file
hooks:
    AfterInstall:
     - location: ./ec_deploy.sh
       runas: webapp
