version: 0.2

phases:
  install:
    commands:
      - |
         if [ -e /tmp/composer.lock ] && [ -e /tmp/vendor.tar ]; then
           diff /tmp/composer.lock ./composer.lock
           if [ $? -eq 0 ]; then
             tar xf /tmp/vendor.tar
           fi
         fi
  build:
    commands:
      - if [ ! -e ./vendor ]; then composer install; fi
      - chmod -R 777 vendor
      - chmod -R 777 storage
      - cp -p .env.example .env
      - php artisan key:generate
      
      - systemctl start mysqld.service
      - php artisan migrate

      - vendor/bin/phpunit
  post_build:
    commands:
      - cp composer.lock /tmp
      - tar cf /tmp/vendor.tar vendor

#artifacts:
#  files:
#    - '**/*'
cache:
  paths:
    - /tmp/composer.lock
    - /tmp/vendor.tar
