version: 0.1

phases:
  install:
    commands:
      - sudo apt-get update -y && sudo apt-get install cmake -y
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - ./vendor/bin/phpunit
