version: 0.1

phases:
  install:
    commands:
      - sudo apt-get update -y && sudo apt-get install cmake -y
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - chmod -R 777 vendor
      - chmod -R 777 storage
      - cp -p .env.example .env
      - php artisan key:generate
      - vendor/bin/phpunit
