version: 0.2

phases:
  install:
    commands:
      - |
         yum install -y tar

         if [ -e /tmp/composer.lock ] && [ -e /tmp/vendor.tar ]; then
           diff /tmp/composer.lock ./composer.lock
           if [ $? -eq 0 ]; then
             tar xf /tmp/vendor.tar
           fi
         fi
         if [ ! -e ./vendor ]; then
           amazon-linux-extras install php7.2 -y
           yum install -y php-mbstring php-xml php-bcmath

           curl -sS https://getcomposer.org/installer | php
           cp composer.phar /usr/local/bin/composer
           ln -s /usr/local/bin/composer /usr/bin/composer

           yum install -y git
           yum install -y zip unzip
         fi
  build:
    commands:
      - if [ ! -e ./vendor ]; then composer install; fi
      - if [ ! -e ./vendor ]; then chmod -R 777 vendor; fi
      - if [ ! -e ./vendor ]; then chmod -R 777 storage; fi
      - if [ ! -e ./vendor ]; then cp -p .env.example .env; fi
      - if [ ! -e ./vendor ]; then php artisan key:generate; fi

   #  - vendor/bin/phpunit
      - phpunit

  post_build:
    commands:
      - cp composer.lock /tmp
      - tar cf /tmp/vendor.tar vendor

#artifacts:
#  files:
#    - '**/*'
cache:
  paths:
    - /tmp/composer.lock
    - /tmp/vendor.tar
